### ISSUE TITLE
No module named 'vnpy_ctp.api.vnctpmd'

### ISSUE THREAD

**Issue by xiongmingzhi** [vnpy/vnpy_ctp#16]
hello, I have install vnpy_ctp,but there is error is No module named 'vnpy_ctp.api.vnctpmd'. I open the file __init__.py it is that 
from .vnctpmd import MdApi
from .vnctptd import TdApi
from .ctp_constant import *_
it not find MdApi, TdApi
Program environment：macos, python3.7

**Comment by Edanflame** [comment]
ctp不支持macos系统
