### ISSUE TITLE
linux 正常安装后无法正常 Import

### ISSUE THREAD

**Issue by ZedRover** [vnpy/vnpy_ctp#23]
设备是 Manjaro 系统，python 3.10，正常安装 vnpy 后无法安装 vnpy_ctp
通过 pip install . 或者 pip install vnpy_ctp 之后都安装正常，但是 import 之后会报错如下

![image](https://user-images.githubusercontent.com/29392414/156765187-3844d952-b067-43a6-a5af-0aaafbf49ee3.png)

**Comment by vnpy** [comment]
目前官方支持的Linux系统只有Ubuntu，查了下这个报错似乎是ARM处理器的问题，CTP接口只有x86/x64的版本
