### ISSUE TITLE
ubuntu python3.10运行ctp接口出错

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy_ctp#24]
操作系统ubuntu20.04

2022-03-13 20:23:12,805  INFO: 交易风控功能启动
2022-03-13 20:23:12,865  INFO: 交易接口:CTP,交易服务器连接成功
2022-03-13 20:23:12,875  INFO: 交易接口:CTP,行情服务器连接成功
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
已放弃 (核心已转储)

**Comment by xldistance** [comment]
bashrc里面加了export LC_ALL="C"也不行

**Comment by vnpy** [comment]
检查下安装中文字符了不？

```
# Install local Chinese language environment
locale-gen zh_CN.GB18030
```

**Comment by xldistance** [comment]
sudo locale-gen zh_CN.GB18030好了
