### ISSUE TITLE
在arm windows 11下无法编译（Mac m1上装的双系统） 求助，急

### ISSUE THREAD

**Issue by JeffQuantFin** [vnpy/vnpy_ctp#28]
求助，急。

Warning D9025   报错  C:\Program Files (x86)\Microsoft Visual 

![报错截图](https://user-images.githubusercontent.com/34833991/163902414-47e83375-95b1-4f09-9ee1-1fe652d3ee59.jpeg)
Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: ????????: "crtdbg.h": No such file or directory

**Comment by vnpy** [comment]
CTP的接口可能不支持ARM架构的系统，暂时没办法了
