### ISSUE TITLE
onRspQryInstrument函数回调时变量data缺失部分字段

### ISSUE THREAD

**Issue by wsdexy** [vnpy/vnpy_ctp#3]
环境
操作系统: Windows 10
Python版本: Python 3.8.5
vn.py版本: 2.2.0
Issue类型：Bug
账户环境：SimNow和实盘均会出现
CTP版本：vnpy原项目中的CTP 6.3.15没有问题，只有本项目中CTP 6.5.1版本会出现此问题

例如，实际登陆时，data变量的实际数据如下：
{'reserve1': 'ZC201C890', 'ExchangeID': 'CZCE', 'InstrumentName': '煤201买权           ', 'reserve2': 'ZC201C890', 'reserve3': 'ZCC', 'ProductClass': '2', 'DeliveryYear': 2021, 'DeliveryMonth': 12, 'MaxMarketOrderVolume': 2, 'MinMarketOrderVolume': 1, 'MaxLimitOrderVolume': 100, 'MinLimitOrderVolume': 1, 'VolumeMultiple': 100, 'PriceTick': 0.1, 'CreateDate': '20210510', 'OpenDate': '20210510', 'ExpireDate': '20211203', 'StartDelivDate': '20211203', 'EndDelivDate': '20211203', 'InstLifePhase': '1', 'IsTrading': 1, 'PositionType': '2', 'PositionDateType': '2', 'LongMarginRatio': 0.0, 'ShortMarginRatio': 0.0, 'MaxMarginSideAlgorithm': '0', 'reserve4': 'ZC201', 'StrikePrice': 890.0, 'OptionsType': '1', 'UnderlyingMultiple': 1.0, 'CombinationType': '0', 'InstrumentID': '', 'ExchangeInstID': '', 'ProductID': '', 'UnderlyingInstrID': '\x1b\x02'}
{'reserve1': 'ZC201P890', 'ExchangeID': 'CZCE', 'InstrumentName': '煤201卖权           ', 'reserve2': 'ZC201P890', 'reserve3': 'ZCP', 'ProductClass': '2', 'DeliveryYear': 2021, 'DeliveryMonth': 12, 'MaxMarketOrderVolume': 2, 'MinMarketOrderVolume': 1, 'MaxLimitOrderVolume': 100, 'MinLimitOrderVolume': 1, 'VolumeMultiple': 100, 'PriceTick': 0.1, 'CreateDate': '20210510', 'OpenDate': '20210510', 'ExpireDate': '20211203', 'StartDelivDate': '20211203', 'EndDelivDate': '20211203', 'InstLifePhase': '1', 'IsTrading': 1, 'PositionType': '2', 'PositionDateType': '2', 'LongMarginRatio': 0.0, 'ShortMarginRatio': 0.0, 'MaxMarginSideAlgorithm': '0', 'reserve4': 'ZC201', 'StrikePrice': 890.0, 'OptionsType': '2', 'UnderlyingMultiple': 1.0, 'CombinationType': '0', 'InstrumentID': '', 'ExchangeInstID': '', 'ProductID': '', 'UnderlyingInstrID': '\x1b\x02'}

调用构建函数
contract = ContractData(
                symbol=data["InstrumentID"],
                exchange=EXCHANGE_CTP2VT[data["ExchangeID"]],
                name=data["InstrumentName"],
                product=product,
                size=data["VolumeMultiple"],
                pricetick=data["PriceTick"],
                gateway_name=self.gateway_name
            )
因“InstrumentID”字段为空，会导致MainEngine中合约数据存储错误，进一步的，订阅行情会报错："行情接口报错，代码：825387374，信息：06"

**Comment by vnpy** [comment]
这个可能是因为用6.5.1连接了老版本柜台（部分期货公司没升级）导致的，请连接新版本的柜台试试看。
