### ISSUE TITLE
无法在m1版mac上安装vnpy_ctp，报错如下

### ISSUE THREAD

**Issue by evimacs** [vnpy/vnpy_ctp#32]
error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13.0-arm64-3.8
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp
      copying vnpy_ctp/__init__.py -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api
      copying vnpy_ctp/api/__init__.py -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api
      copying vnpy_ctp/api/ctp_constant.py -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/gateway
      copying vnpy_ctp/gateway/ctp_gateway.py -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/gateway
      copying vnpy_ctp/gateway/__init__.py -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/gateway
      running egg_info
      writing vnpy_ctp.egg-info/PKG-INFO
      writing dependency_links to vnpy_ctp.egg-info/dependency_links.txt
      writing requirements to vnpy_ctp.egg-info/requires.txt
      writing top-level names to vnpy_ctp.egg-info/top_level.txt
      reading manifest file 'vnpy_ctp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pyd' under directory 'vnpy_ctp'
      adding license file 'LICENSE'
      writing manifest file 'vnpy_ctp.egg-info/SOURCES.txt'
      copying vnpy_ctp/api/libthostmduserapi_se.so -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api
      copying vnpy_ctp/api/libthosttraderapi_se.so -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api
      copying vnpy_ctp/api/thostmduserapi_se.dll -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api
      copying vnpy_ctp/api/thosttraderapi_se.dll -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_header_define.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_header_function.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_header_on.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_header_process.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_source_function.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_source_module.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_source_on.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_source_process.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_source_switch.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_md_source_task.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_header_define.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_header_function.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_header_on.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_header_process.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_source_function.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_source_module.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_source_on.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_source_process.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_source_switch.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      copying vnpy_ctp/api/generator/ctp_td_source_task.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/generator
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/ctp
      copying vnpy_ctp/api/include/ctp/ThostFtdcMdApi.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/ctp
      copying vnpy_ctp/api/include/ctp/ThostFtdcTraderApi.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/ctp
      copying vnpy_ctp/api/include/ctp/ThostFtdcUserApiDataType.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/ctp
      copying vnpy_ctp/api/include/ctp/ThostFtdcUserApiStruct.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/ctp
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/attr.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/buffer_info.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/cast.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/chrono.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/common.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/complex.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/eigen.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/embed.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/eval.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/functional.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/iostream.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/numpy.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/operators.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/options.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/pybind11.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/pytypes.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/stl.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      copying vnpy_ctp/api/include/pybind11/stl_bind.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11/detail
      copying vnpy_ctp/api/include/pybind11/detail/class.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11/detail
      copying vnpy_ctp/api/include/pybind11/detail/common.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11/detail
      copying vnpy_ctp/api/include/pybind11/detail/descr.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11/detail
      copying vnpy_ctp/api/include/pybind11/detail/init.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11/detail
      copying vnpy_ctp/api/include/pybind11/detail/internals.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11/detail
      copying vnpy_ctp/api/include/pybind11/detail/typeid.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/include/pybind11/detail
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/libs
      copying vnpy_ctp/api/libs/thostmduserapi_se.lib -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/libs
      copying vnpy_ctp/api/libs/thosttraderapi_se.lib -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/libs
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp
      copying vnpy_ctp/api/vnctp/vnctp.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctpmd
      copying vnpy_ctp/api/vnctp/vnctpmd/dllmain.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctpmd
      copying vnpy_ctp/api/vnctp/vnctpmd/stdafx.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctpmd
      copying vnpy_ctp/api/vnctp/vnctpmd/stdafx.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctpmd
      copying vnpy_ctp/api/vnctp/vnctpmd/targetver.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctpmd
      copying vnpy_ctp/api/vnctp/vnctpmd/vnctpmd.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctpmd
      copying vnpy_ctp/api/vnctp/vnctpmd/vnctpmd.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctpmd
      creating build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd
      copying vnpy_ctp/api/vnctp/vnctptd/dllmain.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd
      copying vnpy_ctp/api/vnctp/vnctptd/stdafx.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd
      copying vnpy_ctp/api/vnctp/vnctptd/stdafx.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd
      copying vnpy_ctp/api/vnctp/vnctptd/targetver.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd
      copying vnpy_ctp/api/vnctp/vnctptd/vnctptd.cpp -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd
      copying vnpy_ctp/api/vnctp/vnctptd/vnctptd.h -> build/lib.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd
      running build_ext
      building 'vnpy_ctp.api.vnctptd' extension
      creating build/temp.macosx-13.0-arm64-3.8
      creating build/temp.macosx-13.0-arm64-3.8/vnpy_ctp
      creating build/temp.macosx-13.0-arm64-3.8/vnpy_ctp/api
      creating build/temp.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp
      creating build/temp.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -Ivnpy_ctp/api/include -Ivnpy_ctp/api/vnctp -I/Users/evimacs/.pyenv/versions/vnpy_38/include -I/Users/evimacs/.pyenv/versions/3.8.13/include/python3.8 -c vnpy_ctp/api/vnctp/vnctptd/vnctptd.cpp -o build/temp.macosx-13.0-arm64-3.8/vnpy_ctp/api/vnctp/vnctptd/vnctptd.o -O2 -MT
      clang: error: argument to '-MT' is missing (expected 1 value)
      error: command 'clang' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vnpy_ctp
  Running setup.py clean for vnpy_ctp
Failed to build vnpy_ctp

**Comment by vnpy** [comment]
CTP接口不支持mac系统
