### ISSUE TITLE
CTP接口已经支持MacOS平台，是否考虑也接入？

### ISSUE THREAD

**Issue by 2efPer** [vnpy/vnpy_ctp#38]

**Comment by vnpy** [comment]
方便提供下相关资料的链接？

**Comment by vnpy** [comment]
收到，我们来看下如何进行编译支持

**Comment by hongpeng945** [comment]
强烈建议支持，最新版本是669
http://www.sfit.com.cn/DocumentDown/api_3/5_2_2/5_2_2_sub2/TradeapiMduserapi_6.6.9_MacOS_pro.zip

**Comment by vnpy** [comment]
已经完成支持
