### ISSUE TITLE
大商所品种tick过滤问题

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy_ctp#39]
原帖链接https://www.vnpy.com/forum/topic/31511-vnpy-ctpdui-pgye-hua-shi-you-qi-de-mei-ri-shou-ge-tickde-datetimechu-li-you-wen-ti?page=1#pid58990

**Comment by vnpy** [comment]
该问题由于非交易时段连接CTP行情服务器后，触发的行情推送导致

**Comment by vnpy** [comment]
评估下来，为了过滤DCE的特殊情况，给其他所有交易所行情引入额外的计算开销，并不划算。

所以上述问题，不适合在交易接口的onRtnDepthMarketData函数中修改，用户可以自行在策略层进行过滤处理。
