### ISSUE TITLE
Mac Arm芯片编译后无法运行

### ISSUE THREAD

**Issue by BuGTEa** [vnpy/vnpy_ctp#41]
macOS 13.2.1版本，Anaconda Python 3.9版本环境，已安装xcode-select install，源码编译安装无报错。

通过脚本运行时，运行到gateway下的__init__.py中from .vnctpmd import MdApi语句，提示报错：

ImportError: dlopen(/Users/user/PycharmProjects/vnpy_ctp_source/vnpy_ctp/api/vnctpmd.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_libiconv'

**Comment by vnpy** [comment]
请使用Python官方的3.10版本试下

**Comment by BuGTEa** [comment]
官方的3.10版本没有问题，所以是Python 3.9版本不支持吗？

**Comment by vnpy** [comment]
理论上3.9也可以，但目前社区反馈看用Mac自带的3.9环境安装都失败了。

从报错看就是少了_libiconv这个字符串编码转换库，这个库是XCode自带的，所以能编译应该系统里应该就存在。

这块暂时还没法确定原因。

**Comment by BuGTEa** [comment]
我怀疑是Anaconda的问题。

Anaconda 2023.3发布了Python 3.10官方版，把anaconda用conda install python=3.10升级，删掉了所有3.9的自带包，然后重新编译安装vnpy_ctp，依旧报之前的错。

我现在的解决方案是：在anaconda的pip 环境下执行pip install -e . 然后删除api文件下生成的.so文件，然后用官方的python 3.10的pip执行pip install -e . 生成.so文件，这样anaconda下的vnpy_ctp就能用了。

**Comment by vnpy** [comment]
感谢反馈！
