### ISSUE TITLE
ctp传入毫秒除以100的后仅剩一位有效数字,时间数据精度缺失

### ISSUE THREAD

**Issue by TianMingZhiZi0000** [vnpy/vnpy_ctp#42]
在`vnpy_ctp.gateway.ctp_gateway.CtpMdApi`中,传出的`UpdateMillisec'`为三位有效数字
下图是某期货公司接口传入
![image](https://user-images.githubusercontent.com/125286632/231043386-5a3db47b-c3d4-49e8-92f9-cd4b7b4fa927.png)

后续的代码`timestamp :  str  = f" {date_str } {data ['UpdateTime' ]}.{int ( data ['UpdateMillisec' ]/100) }" `中,将三位有效数字变为了一位

**Comment by EzMoney-Sniper** [comment]
同遇到这个问题

**Comment by EzMoney-Sniper** [comment]
可参照https://www.vnpy.com/forum/topic/31067-dui-zheng-shang-suo-xing-qing-shu-ju-zhong-shi-jian-miao-yi-xia-de-bu-fen-jin-xing-bu-chong-de-xiu-gai 代码解决  具体代码为 # 这里错了，按照这样的字符串"%Y%m%d %H:%M:%S.%f"，会错把tick.datetime的微秒当成0.1秒计数
        # timestamp: str = f"{date_str} {data['UpdateTime']}.{int(data['UpdateMillisec']/100)}"        
        timestamp: str = f"{date_str} {data['UpdateTime']}." + str(data['UpdateMillisec']*1000).zfill(6) # hxxjava edit

**Comment by vnpy** [comment]
感谢反馈，我们来测试下，争取下个版本修复

**Comment by vnpy** [comment]
在SimNow和一家期货的测试环境，测试后发现UpdateMillisec的数据依然为0和500这种形式，没有817、890类似的数字出现。

麻烦确认下这边使用的期货公司CTP柜台版本？

**Comment by EzMoney-Sniper** [comment]
晓优哥你用实盘的行情API，测试DCE随便一个品种，就会发现全都是817、890这种格式了

**Comment by EzMoney-Sniper** [comment]
SHFR CZCE CFFEX INE 确实都是整数，就DCE特殊

**Comment by vnpy** [comment]
收到，我们周一来测下

**Comment by vnpy** [comment]
已修复
