### ISSUE TITLE
win10 python39 env,   pip install failed

### ISSUE THREAD

**Issue by happybeta** [vnpy/vnpy_ctp#44]
pip install vnpy_ctp
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting vnpy_ctp
  Using cached https://mirrors.aliyun.com/pypi/packages/91/bf/4ad355e1c0dad86e9c03fcf066ac3dab957d10a899c071b775abde95ca41/vnpy_ctp-6.6.7.2.tar.gz (12.3 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: importlib_metadata in c:\python39\lib\site-packages (from vnpy_ctp) (4.12.0)
Requirement already satisfied: zipp>=0.5 in c:\python39\lib\site-packages (from importlib_metadata->vnpy_ctp) (3.15.0)
Building wheels for collected packages: vnpy_ctp
  Building wheel for vnpy_ctp (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [139 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\vnpy_ctp
      copying vnpy_ctp\__init__.py -> build\lib.win-amd64-3.9\vnpy_ctp
      creating build\lib.win-amd64-3.9\vnpy_ctp\api
      copying vnpy_ctp\api\ctp_constant.py -> build\lib.win-amd64-3.9\vnpy_ctp\api
      copying vnpy_ctp\api\__init__.py -> build\lib.win-amd64-3.9\vnpy_ctp\api
      creating build\lib.win-amd64-3.9\vnpy_ctp\gateway
      copying vnpy_ctp\gateway\ctp_gateway.py -> build\lib.win-amd64-3.9\vnpy_ctp\gateway
      copying vnpy_ctp\gateway\__init__.py -> build\lib.win-amd64-3.9\vnpy_ctp\gateway
      running egg_info
      writing vnpy_ctp.egg-info\PKG-INFO
      writing dependency_links to vnpy_ctp.egg-info\dependency_links.txt
      writing requirements to vnpy_ctp.egg-info\requires.txt
      writing top-level names to vnpy_ctp.egg-info\top_level.txt
      reading manifest file 'vnpy_ctp.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pyd' under directory 'vnpy_ctp'
      adding license file 'LICENSE'
      writing manifest file 'vnpy_ctp.egg-info\SOURCES.txt'
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctpmd
      copying vnpy_ctp\api\vnctp\vnctpmd\vnctpmd.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctpmd
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctptd
      copying vnpy_ctp\api\vnctp\vnctptd\vnctptd.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctptd
      copying vnpy_ctp\api\libthostmduserapi_se.so -> build\lib.win-amd64-3.9\vnpy_ctp\api
      copying vnpy_ctp\api\libthosttraderapi_se.so -> build\lib.win-amd64-3.9\vnpy_ctp\api
      copying vnpy_ctp\api\thostmduserapi_se.dll -> build\lib.win-amd64-3.9\vnpy_ctp\api
      copying vnpy_ctp\api\thosttraderapi_se.dll -> build\lib.win-amd64-3.9\vnpy_ctp\api
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_header_define.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_header_function.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_header_on.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_header_process.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_source_function.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_source_module.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_source_on.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_source_process.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_source_switch.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_md_source_task.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_header_define.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_header_function.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_header_on.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_header_process.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_source_function.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_source_module.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_source_on.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_source_process.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_source_switch.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      copying vnpy_ctp\api\generator\ctp_td_source_task.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\generator
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\include
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\include\ctp
      copying vnpy_ctp\api\include\ctp\ThostFtdcMdApi.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\ctp
      copying vnpy_ctp\api\include\ctp\ThostFtdcTraderApi.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\ctp
      copying vnpy_ctp\api\include\ctp\ThostFtdcUserApiDataType.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\ctp
      copying vnpy_ctp\api\include\ctp\ThostFtdcUserApiStruct.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\ctp
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\ctp
      copying vnpy_ctp\api\include\mac\ctp\ThostFtdcMdApi.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\ctp
      copying vnpy_ctp\api\include\mac\ctp\ThostFtdcTraderApi.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\ctp
      copying vnpy_ctp\api\include\mac\ctp\ThostFtdcUserApiDataType.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\ctp
      copying vnpy_ctp\api\include\mac\ctp\ThostFtdcUserApiStruct.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\ctp
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\attr.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\buffer_info.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\cast.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\chrono.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\common.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\complex.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\eigen.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\embed.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\eval.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\functional.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\iostream.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\numpy.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\operators.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\options.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\pybind11.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\pytypes.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\stl.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      copying vnpy_ctp\api\include\mac\pybind11\stl_bind.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11\detail
      copying vnpy_ctp\api\include\mac\pybind11\detail\class.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11\detail
      copying vnpy_ctp\api\include\mac\pybind11\detail\common.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11\detail
      copying vnpy_ctp\api\include\mac\pybind11\detail\descr.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11\detail
      copying vnpy_ctp\api\include\mac\pybind11\detail\init.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11\detail
      copying vnpy_ctp\api\include\mac\pybind11\detail\internals.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11\detail
      copying vnpy_ctp\api\include\mac\pybind11\detail\typeid.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\mac\pybind11\detail
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\attr.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\buffer_info.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\cast.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\chrono.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\common.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\complex.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\eigen.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\embed.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\eval.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\functional.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\iostream.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\numpy.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\operators.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\options.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\pybind11.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\pytypes.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\stl.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      copying vnpy_ctp\api\include\pybind11\stl_bind.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11\detail
      copying vnpy_ctp\api\include\pybind11\detail\class.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11\detail
      copying vnpy_ctp\api\include\pybind11\detail\common.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11\detail
      copying vnpy_ctp\api\include\pybind11\detail\descr.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11\detail
      copying vnpy_ctp\api\include\pybind11\detail\init.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11\detail
      copying vnpy_ctp\api\include\pybind11\detail\internals.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11\detail
      copying vnpy_ctp\api\include\pybind11\detail\typeid.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\include\pybind11\detail
      creating build\lib.win-amd64-3.9\vnpy_ctp\api\libs
      copying vnpy_ctp\api\libs\libcomunicationkey.a -> build\lib.win-amd64-3.9\vnpy_ctp\api\libs
      copying vnpy_ctp\api\libs\libcrypto.a -> build\lib.win-amd64-3.9\vnpy_ctp\api\libs
      copying vnpy_ctp\api\libs\libssl.a -> build\lib.win-amd64-3.9\vnpy_ctp\api\libs
      copying vnpy_ctp\api\libs\libthostmduserapi_se.a -> build\lib.win-amd64-3.9\vnpy_ctp\api\libs
      copying vnpy_ctp\api\libs\libthosttraderapi_se.a -> build\lib.win-amd64-3.9\vnpy_ctp\api\libs
      copying vnpy_ctp\api\libs\thostmduserapi_se.lib -> build\lib.win-amd64-3.9\vnpy_ctp\api\libs
      copying vnpy_ctp\api\libs\thosttraderapi_se.lib -> build\lib.win-amd64-3.9\vnpy_ctp\api\libs
      copying vnpy_ctp\api\vnctp\vnctp.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp
      copying vnpy_ctp\api\vnctp\vnctpmd\dllmain.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctpmd
      copying vnpy_ctp\api\vnctp\vnctpmd\stdafx.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctpmd
      copying vnpy_ctp\api\vnctp\vnctpmd\stdafx.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctpmd
      copying vnpy_ctp\api\vnctp\vnctpmd\targetver.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctpmd
      copying vnpy_ctp\api\vnctp\vnctpmd\vnctpmd.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctpmd
      copying vnpy_ctp\api\vnctp\vnctptd\dllmain.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctptd
      copying vnpy_ctp\api\vnctp\vnctptd\stdafx.cpp -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctptd
      copying vnpy_ctp\api\vnctp\vnctptd\stdafx.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctptd
      copying vnpy_ctp\api\vnctp\vnctptd\targetver.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctptd
      copying vnpy_ctp\api\vnctp\vnctptd\vnctptd.h -> build\lib.win-amd64-3.9\vnpy_ctp\api\vnctp\vnctptd
      running build_ext
      building 'vnpy_ctp.api.vnctptd' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vnpy_ctp
  Running setup.py clean for vnpy_ctp
Failed to build vnpy_ctp
ERROR: Could not build wheels for vnpy_ctp, which is required to install pyproject.toml-based projects

**Comment by vnpy** [comment]
非 Python 3.10版本，需要有Visual Studio的C++环境来提供编译功能
