### ISSUE TITLE
建议修正gateway.ctp_gateway下的onRtnTrade和onRtnOrder函数中数据的时间戳

### ISSUE THREAD

**Issue by Mjzs12138** [vnpy/vnpy_ctp#56]
onRtnTrade和onRtnOrder中，OrderData和TradeData的dt时间戳定义是"f"{data['InsertDate']} {data['InsertTime']}""。实盘运行发现，对于大商所或郑商所，InsertDate不是实际日期，而是交易日；对于上期所，则是实际日期。建议统一调整为实际日期，避免产生混乱。

**Comment by vnpy** [comment]
请问大商所和郑商所，对应的实际日期字段有吗？

**Comment by Mjzs12138** [comment]
没有研究过，不过修正只需要取当前时刻的实际日期作为日期部分就可以了吧

**Comment by vnpy** [comment]
> 没有研究过，不过修正只需要取当前时刻的实际日期作为日期部分就可以了吧

如果夜盘发生了交易，那么在第二天日盘重启后，接收到委托和成交数据的日期就是错误的了。

之前也是因为这个原因没有采用这个逻辑。
