### ISSUE TITLE
为什么我使用subscribeMarketData函数，程序会自动hold住？

### ISSUE THREAD

**Issue by bitswall** [vnpy/vnpy_ctp#58]
请问一下为什么我使用vnpy_ctp中subscribeMarketData函数，程序会自动hold住不释放进程？

1. 我并没有使用self.event = Event()去主动hold进程。
2. 在初始化的时候，只使用了self.init(），没有使用self.join(）

只要使用subscribeMarketData函数，程序会自动hold住不释放进程。我咨询了一下一些朋友CTP的c++源码，他们说在源码中，没有主动hold这个动作。

这函数导致我其他后续程序都不能正常运行，怎么解决这个问题？ 谢谢！

btw：感觉subscribeMarketData被改写过。原版的subscribeMarketData是可以同时订阅多个合约的。而我使用self.subscribeMarketData(['ag2412', 'au2412'], 2)， 系统会报错如下。这个提示感觉合约参数只能是str，不能是list
TypeError: subscribeMarketData(): incompatible function arguments. The following argument types are supported:
    1. (self: vnpy_ctp.api.vnctpmd.MdApi, arg0: str) -> int

Invoked with: <ctp.ctp.CtpMd object at 0x000001EFB4E05590>, ['ag2412', 'au2412'], 20

**Comment by vnpy** [comment]
请贴下你的subscribeMarketData函数调用相关代码？

**Comment by bitswall** [comment]
关于hold住进程的事情，应该是我自己的程序问题，我自己在排查一下。但subscribe不能同时订阅多个合约，这个一直存在.....

from vnpy_ctp.api import  MdApi

class CtpMd(MdApi):
    def subscribe()：
         ret = self.subscribeMarketData(['ag2412', 'au2412'], 2)
         self.event = Event()
         self.event.clear()
         self.event.wait(10)
    def onRspSubMarketData(self, data: dict, error: dict, reqid: int, islast: bool) -> None:
           if error['ErrorID'] != 0:  # 非0都代表错误
               print(f'{error}')
           if islast:
               self.event.set()
    def onRtnDepthMarketData(self, data: dict) -> None:
        tick = TickData(.....)
        if tick is not None:  # 如果tick有效，则保存到队列
            self.md_tick_queue.put(tick)

系统报这个错误：
TypeError: subscribeMarketData(): incompatible function arguments. The following argument types are supported:
    1. (self: vnpy_ctp.api.vnctpmd.MdApi, arg0: str) -> int

Invoked with: <quantone.ctp.ctp.CtpMd object at 0x000001F076456450>, ['ag2412', 'au2412'], 2

**Comment by vnpy** [comment]
1. subscribeMarketData函数只接收1个合约代码字符串的入参
2. 回调线程由C++线程发起，不能在回调函数下使用Event之类的机制阻塞等待，会造成程序异常

**Comment by bitswall** [comment]
我看原版的c++subscribeMarketData函数是可以接受一个list作为参数的，后面的int是数量。请问vnpy_ctp的subscribeMarketData是改写了原版的函数吗？

**Comment by vnpy** [comment]
> 我看原版的c++subscribeMarketData函数是可以接受一个list作为参数的，后面的int是数量。请问vnpy_ctp的subscribeMarketData是改写了原版的函数吗？我如果想一次通过一个list订阅，一次性订阅多个合约应该怎么做？

对，这个函数vnpy_ctp做了改造，如果想要list方式订阅可以自己调整封装代码中的subscribeMarketData改为list传参
