### ISSUE TITLE
请问vnpy_ctp支持评测环境吗？

### ISSUE THREAD

**Issue by JackieJin1025** [vnpy/vnpy_ctp#60]
通过vnpy_ctp 监听评测环境的行情数据，返回
<img width="633" alt="image" src="https://github.com/user-attachments/assets/63dce861-35f4-4a20-a871-d7497a785acc">

券商那边反馈评测环境api与正式环境不同，请问vnpy_ctp支持评测环境api吗？ 

相关代码
`
    event_engine = EventEngine()

    # 创建主引擎
    main_engine = MainEngine(event_engine)

    # 创建 CTP 网关
    ctp_gateway = CtpGateway(event_engine, "ctp_gateway")

    # 连接 CTP
    ctp_gateway.connect({
        "用户名": "xxxx",
        "密码": "xxxx",
        "经纪商代码": "xxxx",
        "交易服务器": "xxxx",
        "行情服务器": "x"
    })

    # 订阅行情
    ticker = SubscribeRequest(symbol="IM2412", exchange=Exchange.CFFEX)
    # main_engine.add_gateway(ctp_gateway, "ctp_gateway")
    ctp_gateway.subscribe(ticker)

    # 定义行情回调函数
    def on_tick(event: Event):
        tick = event.data
        print(f"Symbol: {tick.symbol}, Last Price: {tick.last_price}, Volume: {tick.volume}")

    # 注册行情回调
    event_engine.register(EVENT_TICK, on_tick)
`

**Comment by vnpy** [comment]
穿透式评测请使用vnpy_ctptest接口
