### ISSUE TITLE
订阅行情数据报错

### ISSUE THREAD

**Issue by JackieJin1025** [vnpy/vnpy_ctp#61]
尝试通过vnpy_ctptest 订阅测试环境行情数据，日志显示能够登入服务器，但报错Segmentation fault。 请问该如何排查？

<img width="576" alt="image" src="https://github.com/user-attachments/assets/eab97ac3-38f2-42c1-a420-820eda876162">

`

from vnpy.event import EventEngine
from vnpy.trader.constant import Exchange
from vnpy.trader.engine import MainEngine
from vnpy.trader.event import EVENT_TICK
from vnpy.trader.object import SubscribeRequest
from vnpy.event.engine import Event
from vnpy.trader.setting import SETTINGS

from vnpy_ctptest import CtptestGateway

import time
from logging import CRITICAL, INFO

SETTINGS["log.level"] = INFO        
event_engine = EventEngine()
main_engine = MainEngine(event_engine)
ctp_gateway = CtptestGateway(event_engine, "ctp_gateway")

ctp_gateway.connect({
    "用户名": "xxx",
    "密码": "xxxx",
    "经纪商代码": "xxxx",
    "交易服务器": "tcp://120.136.159.78:53205",
    "行情服务器": "tcp://120.136.159.78:53213"
})

ticker = SubscribeRequest(symbol="IM2412", exchange=Exchange.CFFEX)
ctp_gateway.subscribe(ticker)

def on_tick(event: Event):
    tick = event.data
    print(f"Symbol: {tick.symbol}, Last Price: {tick.last_price}, Volume: {tick.volume}")

event_engine.register(EVENT_TICK, on_tick)`

**Comment by vnpy** [comment]
1. 发起连接登录后，要等待若干秒接口初始化完毕，才能发起订阅请求
2. 你这里似乎是Docker环境，请检查是否安装了中文编码，否则会导致CTP接口崩溃
