### ISSUE TITLE
无法在Linux中安装vnpy_ctp

### ISSUE THREAD

**Issue by tarzan1112** [vnpy/vnpy_ctp#8]
- 运行环境: 
    - Ubuntu 20.4 LTS
    - Python 3.7
    - pip 21.1.2
    - gcc 9.3.0
- 问题重现步骤: 
     1. 使用 `pip install vnpy_ctp`安装卡住, 按`ctrl+c`取消后, 再次使用`pip install vnpy_ctp -v` 发现卡在warning信息 *"cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++"*
     2. 尝试下载源码后手动编译, 同样在运行`python setup.py install`后, 卡在上述warning
- 问题根源分析: 参考 [stackoverflow的相关文章](https://stackoverflow.com/questions/8106258/cc1plus-warning-command-line-option-wstrict-prototypes-is-valid-for-ada-c-o/49041815#49041815)
个人按照上述文章进行了尝试但由于不熟悉这方面的知识未能成功解决.

详细错误信息:
```
running install
running bdist_egg
running egg_info
writing vnpy_ctp.egg-info/PKG-INFO
writing dependency_links to vnpy_ctp.egg-info/dependency_links.txt
writing requirements to vnpy_ctp.egg-info/requires.txt
writing top-level names to vnpy_ctp.egg-info/top_level.txt
reading manifest file 'vnpy_ctp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'vnpy_ctp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'vnpy_ctp.api.vnctptd' extension
gcc -pthread -B /root/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ivnpy_ctp/api/include -Ivnpy_ctp/api/vnctp -I/root/miniconda3/include/python3.7m -c vnpy_ctp/api/vnctp/vnctptd/vnctptd.cpp -o build/temp.linux-x86_64-3.7/vnpy_ctp/api/vnctp/vnctptd/vnctptd.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
```

**Comment by vnpy** [comment]
这个warning是提示信息，不是报错。

卡住是因为gcc命令会进行API封装的编译工作，取决于CPU和内存这个耗时可能会比较长，多等一会（比如20分钟）看看。

如果还不行推荐换个配置高些的机器试试。
